"""Deterministic rejection of Whisper hallucinations and empty speech.

Runs before any dispatch decision.  The genuine-empty case is already handled
by the caller; these filters cover the far more common failure mode where
Whisper synthesizes plausible-sounding boilerplate or repetition from near-
silence.  All rules are cheap, explicit, and never require a model call.
"""

import re
import unicodedata


HALLUCINATION_PATTERNS = (
    (r"subtitles?\s+by\s+(?:the\s+)?\w+", "captions boilerplate"),
    (r"\[?\b(music|applause|laughter|silence|foreign|noise|inaudible)\b\]?", "background-caption token"),
    (r"\b(thanks|thank you)\s+for\s+(watching|viewing|listening|the\s+watch)\b", "sign-off greeting"),
    (r"\b(please\s+)?(like|subscribe)|like and subscribe|subscription\b", "channel promo"),
    (r"\b(what\s+up\s+guys|hey\s+guys|hello\s+everyone)\s+(welcome|thanks)", "channel intro"),
    (r"\b(welcome back|today.{0,40}going to talk about)\b", "channel intro"),
    (r"\b(sponsored|patreon|\bads\b)\s+by\b", "channel promo"),
    (r"\b(transcript provided|powered by|generated by)\b", "caption boilerplate"),
)


def _normalized(text):
    text = unicodedata.normalize("NFKC", str(text or "")).casefold()
    text = re.sub(r"[^\w\s]", " ", text, flags=re.UNICODE)
    return " ".join(text.split())


def _repeat_ratio(text):
    words = re.findall(r"[\w]+", text)
    if len(words) < 4:
        return 0.0
    unique = set(words)
    return 1.0 - (len(unique) / len(words))


def reject_reason(text):
    """Return a human-readable reason for rejecting ``text``, or ``None``."""
    if not isinstance(text, str):
        return None
    normalized = _normalized(text)
    if not normalized:
        return "empty"
    for pattern, label in HALLUCINATION_PATTERNS:
        if re.search(pattern, normalized):
            return label
    if _repeat_ratio(normalized) > 0.6:
        return "repetitive no-speech sleep"
    return None